---
dist: xenial
sudo: required
language: python
branches:
  only:
    - master
python: '3.7'
cache: pip

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-git daixijun.git
  - cd daixijun.git

install:
  - pip install molecule docker
  - pip install --upgrade testinfra

script:
  - molecule test

notifications:
  email: false
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
